### ISSUE TITLE
Generated Antlr4 grammar is incorrect

### ISSUE THREAD

**Issue by kaby76** [BNFC/bnfc#329] opened 2020-12-30 10:31 UTC
I'm using BNF.cf and bnfc 2.8.4 to generate an Antlr4 grammar which I then strip and use for my extension in a language server. The generated lexer code is syntactically incorrect and not accepted by the Antlr 4.9 tool.

    STRINGTEXT : ~[\"\\] -> more;
    CHARANY     :  ~[\'\\] -> more, mode(CHAREND);

I'm not sure why this isn't accepted by the Antlr grammar, after all, EscAny is in Antlr4's lexer rule. I will investigate further. But I recommend removing the backslashes before the single and double-quotes.

Disregard if this is already fixed.

**Comment by andreasabel** [comment] 2020-12-30 15:33
Thanks @kaby76 for the report!  
Please make sure that isn't already fixed in #319, and released with BNFC 2.9.0.

Should this not be fixed, please provide a MWE in form of a small `.cf` file that allow me to easily reproduce the bug.

**Comment by kaby76** [comment] 2020-12-30 16:15
It is not fixed in v2.9.0, at least not completely. `STRINGTEXT : ~["\\] -> more;` is fine, but `CHARANY     :  ~[\'\\] -> more, mode(CHAREND);` is not.

Here is how to reproduce it from a Bash shell. I assume that you have Git, downloaded antlr-4.9-complete.jar (see https://www.antlr.org/download/index.html), downloaded Java (I have jdk-11.0.4), and placed Java executable on `path` for your OS.

    mkdir temp
    cd temp
    git clone https://github.com/BNFC/bnfc.git --branch v2.9.0 --single-branch
    cd bnfc/source/src
    cp ../BNFC.cf .
    # I assume you are using bnfc 2.9.0 executable--I'm using that for Windows.
    bnfc --java-antlr --force BNFC.cf
    cd bnfc
    # I assume you have downloaded the latest Antlr jar and java on path.
    java -jar ~/Downloads/antlr-4.9-complete.jar *.g4

The output of this is:

    warning(156): bnfcLexer.g4:78:16: invalid escape sequence \'
    Exception in thread "main" java.lang.RuntimeException: set is empty
        at org.antlr.v4.runtime.misc.IntervalSet.getMaxElement(IntervalSet.java:421)
        at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:169)
        at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
        at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
        at org.antlr.v4.Tool.process(Tool.java:369)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
        at org.antlr.v4.Tool.main(Tool.java:172)

**Comment by andreasabel** [comment] 2020-12-30 22:46
Ok, this seems to be a problem with more recent ANTLR versions, it is still ok with 4.5:
```
$ java  org.antlr.v4.Tool 
ANTLR Parser Generator  Version 4.5.1
...
$ java  org.antlr.v4.Tool -lib bnfc -package bnfc bnfc/bnfcLexer.g4
$ java  org.antlr.v4.Tool -lib bnfc -package bnfc bnfc/bnfcParser.g4
```

**Comment by kaby76** [comment] 2020-12-30 23:13
Ok, thanks. That kind of sucks. I'll check out Antlr's source and see what got messed up.

**Comment by andreasabel** [comment] 2020-12-31 15:19
It seems like BNFC is still not implementing the escaping correctly, see the rules at: https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md
According to these rules, a single quote should not be escaped inside brackets (char sets).
```
CHARANY : ~[\'\\] -> more, mode(CHAREND);
```
This is wrong.

I suppose ANTLR got stricter checking the rules.

**Comment by kaby76** [comment] 2020-12-31 15:37
I think it's a regression in the Antlr rules. This stuff was moved into lexer modes, which broke things. My first test using EscAny without modes works fine with `[\'foobar]`, but I'm adding in the rules one by one to figure what broke the grammar. In any case, you might want to generate the single-quote without a backslash.

**Comment by kaby76** [comment] 2020-12-31 21:24
There are at least two Git issues raised and then closed on escaped characters in Antlr: https://github.com/antlr/antlr4/issues/1537 https://github.com/antlr/antlr4/issues/1871 . For `[\']`, the tool gives a warning that it's not valid, but it crashes, which it shouldn't do. It is, apparently, now an invalid escape character, at least in character sets (https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexer-rule-elements).

**Comment by andreasabel** [comment] 2021-01-01 17:25
I am fixing the spurious escaping of `'`s in the ANTLR backend, but I agree that ANTLR should not crash on spurious escaping, just ignore it.

> For `[\']`, the tool gives a warning that it's not valid, but it crashes, which it shouldn't do.

**Closed** 2021-01-01 17:26 UTC
Labels: Java/ANTLR, bug, lexer

**Comment by andreasabel** [comment] 2021-01-04 11:58
Did the fix work for you, @kaby76 ?

**Comment by kaby76** [comment] 2021-01-05 20:02
Yes, that fixed the problem. Thank you. It took me a while to get a build working because I work mostly on Windows in a MINGW64 environment. I could not get the build to work via Cabal (https://github.com/BNFC/bnfc#installing-the-development-version), but `stack install --stack-yaml stack-8.10.3.yaml` worked fine. I was looking to see what you have for nightly builds in order to set up a Windows env for building, but you're using Github Actions only on Linux. And, you have a .travis.yml file, which looks unused, and no Appveyor file.

**Comment by andreasabel** [comment] 2021-01-06 09:36
> I was looking to see what you have for nightly builds in order to set up a Windows env for building, but you're using Github Actions only on Linux. 

PRs welcome!  
The current GHA workflows are automatically generated by Haskell-CI, which does not add macOS or Windows builds.  These could be added manually in a separate `.yaml` file, similar to https://github.com/agda/agda/blob/master/.github/workflows/nightly.yml maybe.

> And, you have a .travis.yml file, which looks unused, and no Appveyor file.

I used to do CI on travis, but am migrating to Github Actions because of the new limitations for OSS builds by travis-ci.
