### ISSUE TITLE
[BUG] Error message while installing BNFC-2.8 on Mac OSX 10.11.3

### ISSUE THREAD

**Issue by xoxota99** [BNFC/bnfc#175] opened 2016-03-19 15:36 UTC
While installing BNFC-2.8-mac.pkg, the following error / warning message is observed: "This package is incompatible with this version of OS X and may fail to install. Installing this package may damage your system, and the installation may fail. To stop the program and the installation, click “Cancel Installation”."

Not willing to take the risk, I can't report on what "damage", if any, results from installation.

**Comment by xoxota99** [comment] 2016-03-19 15:38
Continuing the installation gives the following error message: "The installation failed. The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

**Comment by xoxota99** [comment] 2016-03-19 16:08
Also failing with BNFC-2.7.1

**Comment by gdetrez** [comment] 2016-04-29 10:20
Sorry for not answering before. This looks like a duplicate of #158. You should be able to install the latest release using cabal.

**Closed** 2019-04-29 20:06 UTC
Labels: wontfix
